### ISSUE TITLE
As a content team member I want a way to see high-level metrics from the survey on demand so I can respond to current trends in the survey results. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/10x-MLaaS#14]
## User story 
As a content team member I want a way to see high-level metrics from the survey on demand so I can respond to current trends in the survey results. 

Is this a dashboard?  Something else?
  
## Acceptance criteria
- [ ] Shows trends on search terms, etc. Can we be proactive instead of reactive?
- [ ] Investigate if there are there analytics or feedback gaps.  eg. not currently receiving feedback from mobile users in sitewide survey. How can we better link analytics data (search terms, metadata, behavior, etc.) to the surveys?
- [ ] Make sure to keep in mind there are two opportunities to look at this information: the site wide survey and the page level survey.

**Comment by OpenGlobe** [comment]
This didn't come up in sprint planning today, so I'm going to leave in the 'to-do' list.

**Comment by TiffanyAndrews** [comment]
Archive
