### ISSUE TITLE
As an analyst with Qualtrics access, I want to be able to segment by "Invited on Page" metadata: Page Type and Topic Taxonomy

### ISSUE THREAD

**Issue by DK1999** [18F/10x-MLaaS#21]
## Acceptance Criteria

Custom Embedded Metadata Dimensions exist in Qualtrics:
- [ ] Page Type
- [ ] Taxonomy Level Two
- [ ] Taxonomy Level Three
- [ ] Taxonomy Level Four
- [ ] I can segment with these Dimensions
- [ ] As the taxonomy changes for existing pages these values can be rewritten. (Note, we use page paths sparingly, so pages can move to different sections of the site without a URL change)

**Comment by DK1999** [comment]
##Acceptance Criteria

- Custom Embedded Metadata Dimensions exist in Qualtrics:
-- Page Type
-- Taxonomy Level Two
-- Taxonomy Level Three
-- Taxonomy Level Four
- I can segment with these Dimensions
- As the taxonomy changes for existing pages these values can be rewritten. (Note, we use page paths sparingly, so pages can move to different sections of the site without a URL change)

**Comment by TiffanyAndrews** [comment]
related to: #135
