### ISSUE TITLE
As a Python Master, I need survey ID numbers of two identical versions of the Sitewide Survey. One version will have a handful of human-generated survey responses. The other will be empty.

### ISSUE THREAD

**Issue by DK1999** [18F/10x-MLaaS#23]

**Comment by DK1999** [comment]
This is so the Python Master can test taking responses out of one survey, tagging them, putting them back in to Qualtrics (into empty survey #2) and then into Google Sheets also.

**Comment by DK1999** [comment]
## Acceptance Criteria

- Need to exactly match what Python is expecting
- Survey IDs posted in Slack

**Comment by OpenGlobe** [comment]
I know this was referenced in sprint planning so I added the Sprint 4 label to it.  Feel free to correct!

**Comment by OpenGlobe** [comment]
Amos to correct this card!

**Comment by amoose** [comment]
Here is the Survey ID we'll be working with: `SV_4IL1lhWMo7LhrjD`

I can duplicate and remove all responses once Scott has confirmed it is accurate. 
https://feedback.gsa.gov/jfe/form/SV_4IL1lhWMo7LhrjD

**Comment by mcallistercs** [comment]
Able to download survey responses from Qualtrics and then push to a Google Sheet, but having to do the former with a py script and the latter with an R script. I'd like to run the R script as a sub-process, but the google permissions might make that tricky. Will figure it out!

**Comment by DK1999** [comment]
@mcallistercs Let us know when you are ready to try to put survey responses back INTO Qualtrics. The ticket sort of doesn't match the reality that we are treating that goal as a second phase, and the MVP (to keep it more minimal) is just get processed comments into sheets. When you need a survey that is identical to the one that is collecting, but blank, let us know.

**Comment by mcallistercs** [comment]
@DK1999 I can give that a go after I figure out how to successfully run this R script as a subprocess within Python. That will save you the trouble of having to run two separate scripts in order to get the responses from Qualtrics into Sheets. Then I'll need to plug the HSM classifier in-between those steps. Once that's done, I'll see about getting responses from Sheets and putting them back into Qualtrics.
