### ISSUE TITLE
As a Product Owner, I want to achieve a pilot Qualtrics survey invite that is acceptable to Design and A11y teams so that I can finish the pilot invite.

### ISSUE THREAD

**Issue by DK1999** [18F/10x-MLaaS#28]
## 10x Qualitative Data User story 
As a Product Owner, I want to achieve a pilot Qualtrics survey invite that is acceptable to Design and A11y teams so that I can finish the pilot invite. 

Goal: USA.gov Sitewide (Pop-up) survey is production-ready, and twin survey that can receive from API is ready too. (David / Amos / Maria - Designer/UX Team Lead). Prioritize implementation of using Qualtrics this sprint. 

## Acceptance criteria

- [x] Pause Google Tag Manager
- [x] Get CSS help?  David to talk to designer on implementation tasks (e.g. redesigning the ‘no thank you button’, etc.).  Figure out tabbing / paging issue
- [x] Do we want / need to use site intercept for the invitation?  Could just use JS.  Workflow design (Amos / David).   Look into JS for triggering the survey. 
- [x] **Implement the survey!**

- [x] David to talk to the accessibility team
- [x] Sign off from Dave Stenger
- [x] Sign off from Maria Marrero
- [x] Sign off from Russell O'Neill

**Comment by DK1999** [comment]
@amoose I met with Dave Stenger about a11y and Maria about design this morning.
Maria and I went over a few things. She's gathering some more little tweaks (we ran out of time), and we did some to the buttons on the modal and the Next Previous buttons on my drafts that gets invited from https://usa-stg.gsa.ctacdev.com/green

Dave Stenger would like to see a few things happen before we launch:

1. Focus: For focus on -

[ ] 1.  buttons in the modal
[ ] 2. buttons in the survey
[ ] 3. radio buttons and text fields in the survey

We outline them in thick orange border: outline: #ff8c00 solid 3px;

2. **Tab order in the modal**
He likes that the first tab goes to the Close X. After that, he would like the tab next to go the text, then the Yes link, then the No Thanks link.  (I see the tabindex="0" for every element when inspecting, but not when editing source in Qualtrics. Can you important a new one and override it?  Or - is it going by the order in the DOM because they are all set to zero? And, if so, is the order set by the order in which I created each element in the Creative editor? Like, if one started over and created them in the correct order, would the DOM order and tabbing order thus follow?)

3. We had a contrast issue, but I think we handled it by making the text black in the Yes I'll Help button. So, just the tab order in the modal and style the focus state.

For later, he'd like us to get the No Thanks button to be a single element and for the modal to grab focus when it launches and not allow focus to leave the modal. It turns out that we had launched the VOC tool with the same issue and then discovered it later, and added javascript to fix it. He thinks Chris from my team wrote that, so in theory we can get the script. Hopefully we can find a place to put it so that it can work.
I also notice that, when tabbing on a survey page, after you tab past the Next button, you don't cycle back to the top. You're gone and can't get back.

**Comment by OpenGlobe** [comment]
@DK1999 to update this issue, progress has been made!  Waiting on modal updates with designer, and resolve the focus issue.

**Comment by DK1999** [comment]
The survey is live. Based on the first four responses this afternoon, I am concerned about invite rate (2% sessions vs old rate of 2% every single pageview) and wishing that the embedded data arrived more consistently, especially Site Referrer, which only arrived once.
OK to close.
