### ISSUE TITLE
As a content and analytics team member, I want to have access to the requisite services in order to do my job.

### ISSUE THREAD

**Issue by amoose** [18F/10x-MLaaS#31]
## 10x Qualitative Data User story 
As a \<type of user\>, I want \<a goal\> so that \<benefit\>. 

As a **content and analytics team member**,
I want to **have access to Qualtrics** and possibly IBM Watson
in order to complete my daily tasks.
  
## Acceptance criteria
- [ ] Collect Qualtrics license requirements for Office of Customer Experience
- [ ] Provide OCE with our requirements
- [ ] ...

**Comment by TiffanyAndrews** [comment]
ARCHIVE
