### ISSUE TITLE
As a content/analytics team member, I want to know the value mobile users are receiving from the site.

### ISSUE THREAD

**Issue by amoose** [18F/10x-MLaaS#32]
As a content/analytics team member, I want to know the value mobile users are receiving from the site.
  
...

## Acceptance criteria
- [ ] Survey mobile users
- [ ] Test and confirm usability with mobile devices. 
- [ ] Contact Qualtrics Support, if necessary, regarding iframes and Site Intercept.

**Comment by TiffanyAndrews** [comment]
ARCHIVE
