### ISSUE TITLE
PAB Review Prep

### ISSUE THREAD

**Issue by csmcallister** [18F/10x-MLaaS#44]
## 10x Qualitative Data User story 
As a person that cares about this project, I'd like us to think about the following things to include/be aware of going into the PAB meeting.
  
## 10x/Qualitative Data Management Run Through Follow Up Questions
- How did this change the USAgov team?
     - [ ] Measure time reduction and/or cost avoidance in labeling comments
     - [ ] Show model's classification report on August data (this will show how good it is despite being such a simple model right now!)
- How could others in GSA use it?
     - Anyone with textual data that has been labeled into different categories (e.g. ham vs. spam) could use this to automate classification.
     - By exposing the model and a related database via an API and creating a UI
     on cloud.gov, folks could simply upload some labeled data once, let the model 
     train, and then register their survey tool with the application so that it streams
     survey responses into the application. Survey comment classification would be 
     scheduled to occur as that data streams in, populating the database. The UI
     sits atop this database and provides analytics to the end-user.
- How could other agencies use it?
     - The exact same way
     - [ ] Might be a good idea to ask the DAP team how many federal websites they track.
- Team would like to see a visual of what the product would look like.
     - [ ] Include the UI sketch [here](https://docs.google.com/document/d/14ExRW8OFMJS7o9HxZvCKJKlgmzL0ge3yx5aQIaAkE74/edit#heading=h.9raumalqsxgm) for an idea of what that could look like.
     - [ ] screenshots of the code? I think that was requested.
- How would the $650,000 be spent? 
     - Database development
     - API development (for model(s), database)
          - might want to consider creating an API that could ingest data from 
       non-Qualtrics sources, i.e. whatever the user has
     - Front-end dev for UI
     - cloud.gov hosting
- "how cheap our product would be vs these other products? "
  - https://cloud.gov/pricing/

**Comment by csmcallister** [comment]
This is also interesting if we want to speak to the number federal website users:

![screenshot_20180928-171332](https://user-images.githubusercontent.com/33464354/46305092-683a4300-c57e-11e8-9e8e-81ec3902a390.png)

**Comment by DK1999** [comment]
2.64 billion visits is only pages with DAP code. They don't cover the whole gov.

**Comment by DK1999** [comment]
Here is a before image of comments. Which of these are helpful to our writers for improving or understanding how people use our content?
![image](https://user-images.githubusercontent.com/25777335/46308270-2feb3280-c587-11e8-91c4-c74657343c82.png)

**Comment by DK1999** [comment]
Here is after the HSM has evaluated them.
![image](https://user-images.githubusercontent.com/25777335/46308310-48f3e380-c587-11e8-89b9-6cc0d62726ff.png)

**Comment by DK1999** [comment]
Agencies / Projects with survey comments that are interested in our work:
HHS
USDA / Centers of Excellence
Customer Experience CAP Goals Working Group
GSA via the Office of Customer Experience.

**Comment by DK1999** [comment]
Non-survey usage:
PBS and Fleet Management Contact Center intake
https://www.ftccomplaintassistant.gov/?utm_source=takeaction#crnt&panel1-1
https://consumercomplaints.fcc.gov/hc/en-us
Search.gov

**Comment by DK1999** [comment]
https://www.regulations.gov/

**Comment by DK1999** [comment]
Every single member of congress has a comment box form. White House, too. They must get SO MUCH SPAM.

**Comment by amoose** [comment]
❤️
