### ISSUE TITLE
Market research: compare available ML SaaS solutions to our HSM

### ISSUE THREAD

**Issue by amoose** [18F/10x-MLaaS#56]
## 10x Machine Learning as a Service

As a **member of the MLaaS team**
I want to **know if an available SaaS solution**
will **provide the same (or better) classification of Spam as the HSM**
so that **we can make an informed decision about our solution to OCE**.
  
## Acceptance criteria
- [ ] Compare classification results from HSM to:
  - [x] Amazon SageMaker
  - [ ] IBM Watson
  - [ ] Google Cloud
- [ ] Ensure costs do not exceed $1K/mo at estimated scale (10 models, 20 trainings, 2000 API calls)

**Comment by cacraig** [comment]
Currently investigating AWS Sagemaker. Everything I've seen so far makes it seem like a viable option going forward. I'm going to try to get a demo up and running soon.

**Comment by cacraig** [comment]
I think Sagemaker likely solves a scaling problem, but as our end users are not guaranteed to be data scientists - it may be best to integrate this after we have improved the existing interface for the HSM.   
  
My suggested Sagemaker workflow:  
  
(1) Create and upload training set to S3. 
(2) We would create models in Jypter notebooks to:
    - Train model (init, and optionally thereafter)
    - Pull the latest Qualtrics data.
    - Run classification.
    - Output classified data.
(3) Expose an AWS lambda API endpoint to:
    - classify most recent survey results
(4) Periodically retrain model. 
    - Accept user feedback, and append correctly classified data to training sets in S3. 
    - Nightly Lambda process to re-train model. 

Resources:  
  
https://medium.com/@julsimon/building-a-spam-classifier-pyspark-mllib-vs-sagemaker-xgboost-1980158a900f

https://medium.com/swlh/classify-emails-into-ham-and-spam-using-naive-bayes-classifier-ffddd7faa1ef

https://aws.amazon.com/blogs/machine-learning/call-an-amazon-sagemaker-model-endpoint-using-amazon-api-gateway-and-aws-lambda/
