### ISSUE TITLE
MeL (HSM 2.0 )running in cloud.gov with SecureAuth

### ISSUE THREAD

**Issue by amoose** [18F/10x-MLaaS#59]
## 10x Qualitative Data User story 
As a **analytics team member**
I want a **centralized service**
**for uploading, downloading, classifying and training my survey data.**
so that I **can share the responsibilities and remove the burden from a single point of failure.**
  
## Acceptance criteria
- [ ] Users must authenticate with SecureAuth to reach web interface.
  - [ ] An admin-managed whitelist of email addresses will allow access
- [ ] HSM can run in cloud.gov (eg. hsm.app.cloud.gov)

Resources:
- https://cloud.gov/docs/apps/leveraging-authentication/#using-cloud-gov-authentication

**Comment by TiffanyAndrews** [comment]
ARCHIVE
