### ISSUE TITLE
Improving USAGov Sitewide survey

### ISSUE THREAD

**Issue by DK1999** [18F/10x-MLaaS#62]
## 10x Qualitative Data User story 
As a machine or a content writing person, I want a survey so that asks helpful questions in a way that I can easily interpret the results.

I have a proposed new sitewide survey in Qualtrics.
1) It keeps two important questions from the current survey, for consistency purposes
2) It gets rid of questions that were deemed not helpful
3) It adds questions that get at aspects of the experience most relevant to content writers: usefulness of information, links, and phone numbers
4) Qualitative questions are really different. It breaks it up into two fields: "what were you trying to do" and "why could you accomplish it or why not". Hopefully this will help direct respondents into answering and result in easier to read and machine-read the responses.
5) It takes advantage of the advanced flow capabilities of Qualtrics. For example, different prompt text in front of open ended question fields in order to simplify analysis.
6) At the end, it also asks a question about how to improve our site

I will provide links to the survey.
  
## Acceptance criteria
- [ ]
- [ ]
- [ ]

**Comment by DK1999** [comment]
I would welcome help testing the survey.

**Comment by TiffanyAndrews** [comment]
survey has been implemented been backlogged by USA.gov team
