### ISSUE TITLE
Integrate AWS Sagemaker

### ISSUE THREAD

**Issue by cacraig** [18F/10x-MLaaS#66]
## 10x Qualitative Data User story 
As a user, I want to run robust machine learning operations quickly. 
  
## Acceptance criteria
- [Machine learning operations are performed by AWS Sagemaker]
- [A process exists by which to train models in AWS Sagemaker]
- [Some automated process to retrain exists]
- [Existing cloud tool or CLI tool uses Sagemaker/Lambda API endpoint to retrieve recent classified data + push corrections]
=====

From: https://github.com/18F/10x-MLaaS/issues/56
====
My suggested Sagemaker workflow:

(1) Create and upload training set to S3.
(2) We would create models in Jypter notebooks to:
- Train model (init, and optionally thereafter)
- Pull the latest Qualtrics data.
- Run classification.
- Output classified data.
(3) Expose an AWS lambda API endpoint to:
- classify most recent survey results
(4) Periodically retrain model.
- Accept user feedback, and append correctly classified data to training sets in S3.
- Nightly Lambda process to re-train model.

Resources:

https://medium.com/@julsimon/building-a-spam-classifier-pyspark-mllib-vs-sagemaker-xgboost-1980158a900f

https://medium.com/swlh/classify-emails-into-ham-and-spam-using-naive-bayes-classifier-ffddd7faa1ef

https://aws.amazon.com/blogs/machine-learning/call-an-amazon-sagemaker-model-endpoint-using-amazon-api-gateway-and-aws-lambda/

**Comment by TiffanyAndrews** [comment]
Archive
