### ISSUE TITLE
Make HSM more flexible (Add additional surveys)

### ISSUE THREAD

**Issue by cacraig** [18F/10x-MLaaS#69]
## 10x Qualitative Data User story 
As a data analyst, I want the ability to process other surveys so that I can filter spam for more surveys.
  
## Acceptance criteria
- [x] Make backend code more generic
- [x] Ability to accept a survey ID as a command line arg, and question ID(s) of comment fields (maybe comma separated)
- [x] Date + survey ID appended to classification output file

**Comment by TiffanyAndrews** [comment]
Code has been generalized to accept other survey but it is not centralized. each new survey instance will be a new MeL instance on the user's computer
